spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.scl.service
  registry:
    address: nacos://192.168.0.109:8848
  protocol:
    name: dubbo
    port: -1